<?php
// build_assets.php
// Usage: php build_assets.php
// Scans header.php and footer.php for local CSS/JS includes, concatenates and minifies them

$root = realpath(__DIR__ . '/..');
$header = __DIR__ . '/header.php';
$footer = __DIR__ . '/footer.php';
$assetsDir = $root . '/assets';
if (!is_dir($assetsDir)) {
    if (!mkdir($assetsDir, 0755, true)) {
        fwrite(STDERR, "Failed to create assets directory: $assetsDir\n");
        exit(1);
    }
}

$filesContent = '';
$cssFiles = array();
$jsFiles = array();

$filesToScan = array();
if (file_exists($header)) $filesToScan[] = $header;
if (file_exists($footer)) $filesToScan[] = $footer;

foreach ($filesToScan as $fpath) {
    $txt = file_get_contents($fpath);

    // match href="<?php echo $baseUrl; ?>/path/to/file.css?ver=..."
    if (preg_match_all('/href="\s*<\?php\s+echo\s+\$baseUrl;\s*;\s*\?>\s*\/([^"\']+?)"/i', $txt, $m)) {
        foreach ($m[1] as $rel) {
            $rel = preg_replace('/\?.*$/', '', $rel);
            $rel = ltrim($rel, '/');
            $cssFiles[] = $root . '/' . $rel;
        }
    }
    if (preg_match_all('/src="\s*<\?php\s+echo\s+\$baseUrl;\s*;\s*\?>\s*\/([^"\']+?)"/i', $txt, $m2)) {
        foreach ($m2[1] as $rel) {
            $rel = preg_replace('/\?.*$/', '', $rel);
            $rel = ltrim($rel, '/');
            $jsFiles[] = $root . '/' . $rel;
        }
    }

    // match href="/path/to/file.css" (site-relative)
    if (preg_match_all('/href="\s*\/(?!\/)([^"\']+?)"/i', $txt, $m3)) {
        foreach ($m3[1] as $rel) {
            // ignore full URLs
            if (preg_match('#^https?://#i', $rel)) continue;
            $rel = preg_replace('/\?.*$/', '', $rel);
            $rel = ltrim($rel, '/');
            $cssFiles[] = $root . '/' . $rel;
        }
    }
    if (preg_match_all('/src="\s*\/(?!\/)([^"\']+?)"/i', $txt, $m4)) {
        foreach ($m4[1] as $rel) {
            if (preg_match('#^https?://#i', $rel)) continue;
            $rel = preg_replace('/\?.*$/', '', $rel);
            $rel = ltrim($rel, '/');
            $jsFiles[] = $root . '/' . $rel;
        }
    }
}

// Deduplicate and filter existing files and types
$tmp = array();
foreach ($cssFiles as $p) {
    if (preg_match('/\.css$/i', $p) && file_exists($p)) {
        $tmp[] = $p;
    }
}
$cssFiles = array_values(array_unique($tmp));
$tmp = array();
foreach ($jsFiles as $p) {
    if (preg_match('/\.js$/i', $p) && file_exists($p)) {
        $tmp[] = $p;
    }
}
$jsFiles = array_values(array_unique($tmp));

function minify_css($s) {
    $s = preg_replace('!/\*.*?\*/!s', '', $s);
    $s = preg_replace('/\s+/', ' ', $s);
    $s = str_replace(array("\n", "\r", "\t"), '', $s);
    $s = preg_replace('/\s*([{};:,])\s*/', '$1', $s);
    $s = preg_replace('/;}/', '}', $s);
    return trim($s);
}

function minify_js($s) {
    // very simple minifier: remove block comments and single-line comments, collapse whitespace
    $s = preg_replace('!/\*.*?\*/!s', '', $s);
    // Remove // comments that start a line or are preceded by whitespace
    $s = preg_replace('/(^|\s)\/\/.*$/m', '$1', $s);
    $s = preg_replace('/\s+/', ' ', $s);
    $s = str_replace(array("\n", "\r", "\t"), '', $s);
    return trim($s);
}

// Build CSS
$combinedCssPath = $assetsDir . '/styles.min.css';
$combinedJsPath = $assetsDir . '/scripts.min.js';

if (!empty($cssFiles)) {
    $out = "/* Combined CSS - generated by build_assets.php */\n";
    foreach ($cssFiles as $c) {
        $content = file_get_contents($c);
        $out .= "\n/* from: $c */\n" . $content . "\n";
    }
    $min = minify_css($out);
    if (file_put_contents($combinedCssPath, $min) === false) {
        fwrite(STDERR, "Failed to write $combinedCssPath\n");
    } else {
        echo "Written: $combinedCssPath (" . count($cssFiles) . " files)\n";
    }
} else {
    echo "No local CSS files found to combine.\n";
}

if (!empty($jsFiles)) {
    $out = "/* Combined JS - generated by build_assets.php */\n";
    foreach ($jsFiles as $j) {
        $content = file_get_contents($j);
        $out .= "\n/* from: $j */\n" . $content . "\n";
    }
    $min = minify_js($out);
    if (file_put_contents($combinedJsPath, $min) === false) {
        fwrite(STDERR, "Failed to write $combinedJsPath\n");
    } else {
        echo "Written: $combinedJsPath (" . count($jsFiles) . " files)\n";
    }
} else {
    echo "No local JS files found to combine.\n";
}

echo "Done.\n";
