<?php
class Config {
    const stopWords = [
        "web design",
        "seo",
        "SEO",
        "DIGITAL MARKETING",
        "errors",
        "SEO Audit",
        "traffic",
        "ranking",
      "increased",
      "leads",
      "more people",
      "more traffic",
      "google seo",
      "promotion",
      "video",
      "web",
      "marketing",
      "award",
      "http",
      "directory",
      "winning",
      "article",
      "competitor",
      "no-cost",
      "trial",
      "ai-powered",
      "noticed",
      "estimator",
      "high quality",
      "link builder",
      "link building",
      "article submission",
      "website’s visibility",
      "google ranking",
      "seo plan",
      "more people visiting",
      "audit",
      "seo",
      "tinyurl"
    ];
}
?>